/*
 * This file was generated by dbusxml2cpp version 0.6
 * Command line was: dbusxml2cpp DeviceThreadFactory.xml -a DeviceThreadFactoryAdaptor -c DeviceThreadFactoryAdaptor
 *
 * dbusxml2cpp is Copyright (C) 2008 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "DeviceThreadFactoryAdaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class DeviceThreadFactoryAdaptor
 */

DeviceThreadFactoryAdaptor::DeviceThreadFactoryAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

DeviceThreadFactoryAdaptor::~DeviceThreadFactoryAdaptor()
{
    // destructor
}

int DeviceThreadFactoryAdaptor::threadCount() const
{
    // get the value of property threadCount
    return qvariant_cast< int >(parent()->property("threadCount"));
}

QStringList DeviceThreadFactoryAdaptor::threads() const
{
    // get the value of property threads
    return qvariant_cast< QStringList >(parent()->property("threads"));
}

