/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -c TApplicationAdaptor tapplication_adaptor.xml -a TApplicationAdaptor
 *
 * qdbusxml2cpp is Copyright (C) 2010 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "TApplicationAdaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class TApplicationAdaptor
 */

TApplicationAdaptor::TApplicationAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

TApplicationAdaptor::~TApplicationAdaptor()
{
    // destructor
}

QStringList TApplicationAdaptor::parameters()
{
    // handle method call it.elettra.trieste.TApplicationsInterface.arguments
    QStringList out0;
    QMetaObject::invokeMethod(parent(), "parameters", Q_RETURN_ARG(QStringList, out0));
    return out0;
}

QString TApplicationAdaptor::executable()
{
    // handle method call it.elettra.trieste.TApplicationsInterface.executable
    QString out0;
    QMetaObject::invokeMethod(parent(), "executable", Q_RETURN_ARG(QString, out0));
    return out0;
}

QDBusVariant TApplicationAdaptor::invokeMethod0(const QString &widgetName, const QString &member)
{
    // handle method call it.elettra.trieste.TApplicationsInterface.invokeMethod0
    QVariant value;
    QMetaObject::invokeMethod(parent(), "invokeMethod0", Q_RETURN_ARG(QVariant, value), Q_ARG(QString, widgetName), Q_ARG(QString, member));
    return QDBusVariant(value);
}


QDBusVariant TApplicationAdaptor::invokeMethod2(const QString &widgetName, const QString &member, const QDBusVariant &val0, const QDBusVariant &val1)
{
    // handle method call it.elettra.trieste.TApplicationsInterface.invokeMethod2
    QVariant value, v1 = val1.variant(), v0 = val0.variant();
    QMetaObject::invokeMethod(parent(), "invokeMethod2", Q_RETURN_ARG(QVariant, value), Q_ARG(QString, widgetName), Q_ARG(QString, member), Q_ARG(QVariant, v0), Q_ARG(QVariant, v1));
    return QDBusVariant(value);
}

QDBusVariant TApplicationAdaptor::invokeMethod3(const QString &widgetName, const QString &member, const QDBusVariant &val0, const QDBusVariant &val1, const QDBusVariant &val2)
{
    // handle method call it.elettra.trieste.TApplicationsInterface.invokeMethod3
    QVariant value, v0 = val0.variant(),  v1 = val1.variant(), v2 = val2.variant();
    QMetaObject::invokeMethod(parent(), "invokeMethod3", Q_RETURN_ARG(QVariant, value), Q_ARG(QString, widgetName), Q_ARG(QString, member), Q_ARG(QVariant, v0), Q_ARG(QVariant, v1), Q_ARG(QVariant, v2));
    return QDBusVariant(value);
}

QDBusVariant TApplicationAdaptor::invokeMethod4(const QString &widgetName, const QString &member, const QDBusVariant &val0, const QDBusVariant &val1, const QDBusVariant &val2, const QDBusVariant &val3)
{
    // handle method call it.elettra.trieste.TApplicationsInterface.invokeMethod4
    QVariant value, v0 = val0.variant(),  v1 = val1.variant(), v2 = val2.variant(), v3 = val3.variant();
    QMetaObject::invokeMethod(parent(), "invokeMethod4", Q_RETURN_ARG(QVariant, value), Q_ARG(QString, widgetName), Q_ARG(QString, member), Q_ARG(QVariant, v0), Q_ARG(QVariant, v1), Q_ARG(QVariant, v2), Q_ARG(QVariant, v3));
    return QDBusVariant(value);
}

QDBusVariant TApplicationAdaptor::invokeMethod5(const QString &widgetName, const QString &member, const QDBusVariant &val0, const QDBusVariant &val1, const QDBusVariant &val2, const QDBusVariant &val3, const QDBusVariant &val4)
{
    // handle method call it.elettra.trieste.TApplicationsInterface.invokeMethod5
    QVariant value, v0 = val0.variant(),  v1 = val1.variant(), v2 = val2.variant(), v3 = val3.variant(), v4 = val4.variant();
    QMetaObject::invokeMethod(parent(), "invokeMethod5", Q_RETURN_ARG(QVariant, value), Q_ARG(QString, widgetName), Q_ARG(QString, member), Q_ARG(QVariant, v0), Q_ARG(QVariant, v1), Q_ARG(QVariant, v2), Q_ARG(QVariant, v3), Q_ARG(QVariant, v4));
    return QDBusVariant(value);
}

QDBusVariant TApplicationAdaptor::readProperty(const QString &objectName, const QString &propertyName)
{
    // handle method call it.elettra.trieste.TApplicationsInterface.readProperty
    QVariant value;
    QMetaObject::invokeMethod(parent(), "readProperty", Q_RETURN_ARG(QVariant, value), Q_ARG(QString, objectName), Q_ARG(QString, propertyName));
    return QDBusVariant(value);
}

void TApplicationAdaptor::writeProperty(const QString &objectName, const QString &propertyName, const QDBusVariant &value)
{
    // handle method call it.elettra.trieste.TApplicationsInterface.setProperty
    QVariant argument = value.variant();
    QMetaObject::invokeMethod(parent(), "writeProperty", Q_ARG(QString, objectName), Q_ARG(QString, propertyName), Q_ARG(QVariant, argument));
}

QDBusVariant TApplicationAdaptor::invokeMethod1(const QString &widgetName, const QString &member, const QDBusVariant &val0)
{
    // handle method call it.elettra.trieste.TApplicationsInterface.invokeMethod1
    QVariant value, v0 = val0.variant();
    QMetaObject::invokeMethod(parent(), "invokeMethod1", Q_RETURN_ARG(QVariant, value), Q_ARG(QString, widgetName), Q_ARG(QString, member), Q_ARG(QVariant, v0));
    return QDBusVariant(value);
}


void TApplicationAdaptor::message()
{
    // handle method call it.elettra.trieste.TApplicationsInterface.message
    QMetaObject::invokeMethod(parent(), "message");
}

QStringList TApplicationAdaptor::methods(const QString &widgetName)
{
    // handle method call it.elettra.trieste.TApplicationsInterface.methods
    QStringList out0;
    QMetaObject::invokeMethod(parent(), "methods", Q_RETURN_ARG(QStringList, out0), Q_ARG(QString, widgetName));
    return out0;
}

QStringList TApplicationAdaptor::properties(const QString &widgetName)
{
    // handle method call it.elettra.trieste.TApplicationsInterface.properties
    QStringList out0;
    QMetaObject::invokeMethod(parent(), "properties", Q_RETURN_ARG(QStringList, out0), Q_ARG(QString, widgetName));
    return out0;
}

void TApplicationAdaptor::quit()
{
    QMetaObject::invokeMethod(parent(), "quit");
}

void TApplicationAdaptor::raise()
{
    // handle method call it.elettra.trieste.TApplicationsInterface.raise
    QMetaObject::invokeMethod(parent(), "raise");
}

void TApplicationAdaptor::onSecondInstanceDetected()
{
    // handle method call it.elettra.trieste.TApplicationsInterface.onSecondInstanceDetected
    QMetaObject::invokeMethod(parent(), "onSecondInstanceDetected");
}

QString TApplicationAdaptor::version()
{
    // handle method call it.elettra.trieste.TApplicationsInterface.version
    QString out0;
    QMetaObject::invokeMethod(parent(), "version", Q_RETURN_ARG(QString, out0));
    return out0;
}

QStringList TApplicationAdaptor::widgetList()
{
    // handle method call it.elettra.trieste.TApplicationsInterface.widgetList
    QStringList out0;
    QMetaObject::invokeMethod(parent(), "widgetList", Q_RETURN_ARG(QStringList, out0));
    return out0;
}


bool TApplicationAdaptor::unique() const
{
    // get the value of property unique
    return qvariant_cast< bool >(parent()->property("unique"));
}

void TApplicationAdaptor::setUnique(bool value)
{
    // set the value of property unique
    parent()->setProperty("unique", qVariantFromValue(value));
}

