Document: qtango
Title: Debian qtango Manual
Author: <insert document author here>
Abstract: This manual describes what qtango is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/qtango/qtango.sgml.gz

Format: postscript
Files: /usr/share/doc/qtango/qtango.ps.gz

Format: text
Files: /usr/share/doc/qtango/qtango.text.gz

Format: HTML
Index: /usr/share/doc/qtango/html/index.html
Files: /usr/share/doc/qtango/html/*.html
